name: Checks
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Checkout'
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 'Setup npm with GitHub credentials'
        run: |
          npm set @leegodden:registry=https://npm.pkg.github.com/leegodden
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.UBER_LG62 }}"

      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap

      - name: Run tests
        run: npx lerna exec npm run test
